const DEFAULT_NUM_RESULTS = 20;
const DEFAULT_AI_TEMPERATURE = 0.2;
const DEFAULT_ENABLE_HOMEPAGE = true;
const DEFAULT_ENABLE_SIMILAR = true;
const DEFAULT_INCLUDE_ADULT = false;
const DEFAULT_SIMILAR_NUM_RESULTS = 15;

module.exports = {
  DEFAULT_NUM_RESULTS,
  DEFAULT_AI_TEMPERATURE,
  DEFAULT_ENABLE_HOMEPAGE,
  DEFAULT_ENABLE_SIMILAR,
  DEFAULT_INCLUDE_ADULT,
  DEFAULT_SIMILAR_NUM_RESULTS,
};
